# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

songs = Song.create([
{color:'orange', genre:'country', url:''},
{color:'orange', genre:'country', url:''},
{color:'orange', genre:'country', url:''},
{color:'orange', genre:'country', url:''},
{color:'orange', genre:'country', url:''},
{color:'orange', genre:'country', url:''},
{color:'yellow', genre:'country', url:''},
{color:'yellow', genre:'country', url:''},
{color:'yellow', genre:'country', url:''},
{color:'yellow', genre:'country', url:''},
{color:'yellow', genre:'country', url:''},
{color:'yellow', genre:'country', url:''},
{color:'yellow', genre:'country', url:''},
{color:'purple', genre:'country', url:''},
{color:'purple', genre:'country', url:''},
{color:'purple', genre:'country', url:''},
{color:'purple', genre:'country', url:''},
{color:'purple', genre:'country', url:''},
{color:'pink', genre:'country', url:''},
{color:'pink', genre:'country', url:''},
{color:'pink', genre:'country', url:''},
{color:'pink', genre:'country', url:''},
{color:'blue', genre:'country', url:''},
{color:'blue', genre:'country', url:''},
{color:'blue', genre:'country', url:''},
{color:'blue', genre:'country', url:''},
{color:'blue', genre:'country', url:''},
{color:'green', genre:'country', url:''},
{color:'green', genre:'country', url:''},
{color:'green', genre:'country', url:''},
{color:'green', genre:'country', url:''},
{color:'green', genre:'country', url:''},
{color:'green', genre:'country', url:''},
{color:'Orange', genre:'alt rock', url:''},
{color:'Orange', genre:'alt rock', url:''},
{color:'Orange', genre:'alt rock', url:''},
{color:'pink', genre:'alt rock', url:''},
{color:'pink', genre:'alt rock', url:''},
{color:'pink', genre:'alt rock', url:''},
{color:'red', genre:'alt rock', url:''},
{color:'red', genre:'alt rock', url:''},
{color:'red', genre:'alt rock', url:''},
{color:'blue', genre:'alt rock', url:''},
{color:'blue', genre:'alt rock', url:''},
{color:'blue', genre:'alt rock', url:''},
{color:'blue', genre:'alt rock', url:''},
{color:'blue', genre:'alt rock', url:''},
{color:'green', genre:'alt rock', url:''},
{color:'green', genre:'alt rock', url:''},
{color:'green', genre:'alt rock', url:''},
{color:'green', genre:'alt rock', url:''},
{color:'green', genre:'alt rock', url:''},
{color:'yellow', genre:'alt rock', url:''},
{color:'yellow', genre:'alt rock', url:''},
{color:'yellow', genre:'alt rock', url:''},
{color:'purple', genre:'alt rock', url:''},
{color:'purple', genre:'alt rock', url:''},
{color:'purple', genre:'alt rock', url:''},
{color:'purple', genre:'alt rock', url:''},
{color:'orange', genre:'jazz', url:''},
{color:'orange', genre:'jazz', url:''},
{color:'orange', genre:'jazz', url:''},
{color:'orange', genre:'jazz', url:''},
{color:'orange', genre:'jazz', url:''},
{color:'yellow', genre:'jazz', url:''},
{color:'yellow', genre:'jazz', url:''},
{color:'yellow', genre:'jazz', url:''},
{color:'yellow', genre:'jazz', url:''},
{color:'yellow', genre:'jazz', url:''},
{color:'blue', genre:'jazz', url:''},
{color:'blue', genre:'jazz', url:''},
{color:'blue', genre:'jazz', url:''},
{color:'blue', genre:'jazz', url:''},
{color:'blue', genre:'jazz', url:''},
{color:'green', genre:'jazz', url:''},
{color:'green', genre:'jazz', url:''},
{color:'green', genre:'jazz', url:''},
{color:'green', genre:'jazz', url:''},
{color:'green', genre:'jazz', url:''},
{color:'pink', genre:'jazz', url:''},
{color:'pink', genre:'jazz', url:''},
{color:'pink', genre:'jazz', url:''},
{color:'pink', genre:'jazz', url:''},
{color:'pink', genre:'jazz', url:''},
{color:'purple', genre:'jazz', url:''},
{color:'purple', genre:'jazz', url:''},
{color:'purple', genre:'jazz', url:''},
{color:'purple', genre:'jazz', url:''},
{color:'purple', genre:'jazz', url:''},

{color:'red', genre:'rap', url:''},
{color:'red', genre:'rap', url:''},
{color:'red', genre:'rap', url:''},
{color:'red', genre:'rap', url:''},
{color:'red', genre:'rap', url:''},
{color:'orange', genre:'rap', url:''},
{color:'orange', genre:'rap', url:''},
{color:'orange', genre:'rap', url:''},
{color:'orange', genre:'rap', url:''},
{color:'orange', genre:'rap', url:''},
{color:'yellow', genre:'rap', url:''},
{color:'yellow', genre:'rap', url:''},
{color:'yellow', genre:'rap', url:''},
{color:'yellow', genre:'rap', url:''},
{color:'yellow', genre:'rap', url:''},
{color:'green', genre:'rap', url:''},
{color:'green', genre:'rap', url:''},
{color:'green', genre:'rap', url:''},
{color:'green', genre:'rap', url:''},
{color:'green', genre:'rap', url:''},
{color:'blue', genre:'rap', url:''},
{color:'blue', genre:'rap', url:''},
{color:'blue', genre:'rap', url:''},
{color:'blue', genre:'rap', url:''},
{color:'blue', genre:'rap', url:''},
{color:'purple', genre:'rap', url:''},
{color:'purple', genre:'rap', url:''},
{color:'purple', genre:'rap', url:''},
{color:'purple', genre:'rap', url:''},
{color:'purple', genre:'rap', url:''},
{color:'pink', genre:'rap', url:''},
{color:'pink', genre:'rap', url:''},
{color:'pink', genre:'rap', url:''},
{color:'pink', genre:'rap', url:''},
{color:'pink', genre:'rap', url:''},

{color:'orange', genre:'folk', url:''},
{color:'orange', genre:'folk', url:''},
{color:'orange', genre:'folk', url:''},
{color:'orange', genre:'folk', url:''},
{color:'orange', genre:'folk', url:''},
{color:'yellow', genre:'folk', url:''},
{color:'yellow', genre:'folk', url:''},
{color:'yellow', genre:'folk', url:''},
{color:'yellow', genre:'folk', url:''},
{color:'yellow', genre:'folk', url:''},
{color:'green', genre:'folk', url:''},
{color:'green', genre:'folk', url:''},
{color:'green', genre:'folk', url:''},
{color:'green', genre:'folk', url:''},
{color:'green', genre:'folk', url:''},
{color:'blue', genre:'folk', url:''},
{color:'blue', genre:'folk', url:''},
{color:'blue', genre:'folk', url:''},
{color:'blue', genre:'folk', url:''},
{color:'blue', genre:'folk', url:''},
{color:'purple', genre:'folk', url:''},
{color:'purple', genre:'folk', url:''},
{color:'purple', genre:'folk', url:''},
{color:'purple', genre:'folk', url:''},
{color:'purple', genre:'folk', url:''},
{color:'pink', genre:'folk', url:''},
{color:'pink', genre:'folk', url:''},
{color:'pink', genre:'folk', url:''},
{color:'pink', genre:'folk', url:''},
{color:'pink', genre:'folk', url:''},

{color:'orange', genre:'rock', url:''},
{color:'orange', genre:'rock', url:''},
{color:'orange', genre:'rock', url:''},
{color:'orange', genre:'rock', url:''},
{color:'orange', genre:'rock', url:''},
{color:'yellow', genre:'rock', url:''},
{color:'yellow', genre:'rock', url:''},
{color:'yellow', genre:'rock', url:''},
{color:'yellow', genre:'rock', url:''},
{color:'yellow', genre:'rock', url:''},
{color:'green', genre:'rock', url:''},
{color:'green', genre:'rock', url:''},
{color:'green', genre:'rock', url:''},
{color:'green', genre:'rock', url:''},
{color:'green', genre:'rock', url:''},
{color:'blue', genre:'rock', url:''},
{color:'blue', genre:'rock', url:''},
{color:'blue', genre:'rock', url:''},
{color:'blue', genre:'rock', url:''},
{color:'blue', genre:'rock', url:''},
{color:'purple', genre:'rock', url:''},
{color:'purple', genre:'rock', url:''},
{color:'purple', genre:'rock', url:''},
{color:'purple', genre:'rock', url:''},
{color:'purple', genre:'rock', url:''},
{color:'pink', genre:'rock', url:''},
{color:'pink', genre:'rock', url:''},
{color:'pink', genre:'rock', url:''},
{color:'pink', genre:'rock', url:''},
{color:'pink', genre:'rock', url:''},

{color:'orange', genre:'indie', url:''},
{color:'orange', genre:'indie', url:''},
{color:'orange', genre:'indie', url:''},
{color:'orange', genre:'indie', url:''},
{color:'orange', genre:'indie', url:''},
{color:'yellow', genre:'indie', url:''},
{color:'yellow', genre:'indie', url:''},
{color:'yellow', genre:'indie', url:''},
{color:'yellow', genre:'indie', url:''},
{color:'yellow', genre:'indie', url:''},
{color:'green', genre:'indie', url:''},
{color:'green', genre:'indie', url:''},
{color:'green', genre:'indie', url:''},
{color:'green', genre:'indie', url:''},
{color:'green', genre:'indie', url:''},
{color:'blue', genre:'indie', url:''},
{color:'blue', genre:'indie', url:''},
{color:'blue', genre:'indie', url:''},
{color:'blue', genre:'indie', url:''},
{color:'blue', genre:'indie', url:''},
{color:'purple', genre:'indie', url:''},
{color:'purple', genre:'indie', url:''},
{color:'purple', genre:'indie', url:''},
{color:'purple', genre:'indie', url:''},
{color:'purple', genre:'indie', url:''},
{color:'pink', genre:'indie', url:''},
{color:'pink', genre:'indie', url:''},
{color:'pink', genre:'indie', url:''},
{color:'pink', genre:'indie', url:''},
{color:'pink', genre:'indie', url:''},

{color:'orange', genre:'blues', url:''},
{color:'orange', genre:'blues', url:''},
{color:'orange', genre:'blues', url:''},
{color:'orange', genre:'blues', url:''},
{color:'orange', genre:'blues', url:''},
{color:'yellow', genre:'blues', url:''},
{color:'yellow', genre:'blues', url:''},
{color:'yellow', genre:'blues', url:''},
{color:'yellow', genre:'blues', url:''},
{color:'yellow', genre:'blues', url:''},
{color:'green', genre:'blues', url:''},
{color:'green', genre:'blues', url:''},
{color:'green', genre:'blues', url:''},
{color:'green', genre:'blues', url:''},
{color:'green', genre:'blues', url:''},
{color:'blue', genre:'blues', url:''},
{color:'blue', genre:'blues', url:''},
{color:'blue', genre:'blues', url:''},
{color:'blue', genre:'blues', url:''},
{color:'blue', genre:'blues', url:''},
{color:'purple', genre:'blues', url:''},
{color:'purple', genre:'blues', url:''},
{color:'purple', genre:'blues', url:''},
{color:'purple', genre:'blues', url:''},
{color:'purple', genre:'blues', url:''},
{color:'pink', genre:'blues', url:''},
{color:'pink', genre:'blues', url:''},
{color:'pink', genre:'blues', url:''},
{color:'pink', genre:'blues', url:''},
{color:'pink', genre:'blues', url:''},

{color:'orange', genre:'Classical', url:''},
{color:'orange', genre:'Classical', url:''},
{color:'orange', genre:'Classical', url:''},
{color:'orange', genre:'Classical', url:''},
{color:'orange', genre:'Classical', url:''},
{color:'yellow', genre:'Classical', url:''},
{color:'yellow', genre:'Classical', url:''},
{color:'yellow', genre:'Classical', url:''},
{color:'yellow', genre:'Classical', url:''},
{color:'yellow', genre:'Classical', url:''},
{color:'green', genre:'Classical', url:''},
{color:'green', genre:'Classical', url:''},
{color:'green', genre:'Classical', url:''},
{color:'green', genre:'Classical', url:''},
{color:'green', genre:'Classical', url:''},
{color:'blue', genre:'Classical', url:''},
{color:'blue', genre:'Classical', url:''},
{color:'blue', genre:'Classical', url:''},
{color:'blue', genre:'Classical', url:''},
{color:'blue', genre:'Classical', url:''},
{color:'purple', genre:'Classical', url:''},
{color:'purple', genre:'Classical', url:''},
{color:'purple', genre:'Classical', url:''},
{color:'purple', genre:'Classical', url:''},
{color:'purple', genre:'Classical', url:''},
{color:'pink', genre:'Classical', url:''},
{color:'pink', genre:'Classical', url:''},
{color:'pink', genre:'Classical', url:''},
{color:'pink', genre:'Classical', url:''},
{color:'pink', genre:'Classical', url:''},

{color:'orange', genre:'Dance', url:''},
{color:'orange', genre:'Dance', url:''},
{color:'orange', genre:'Dance', url:''},
{color:'orange', genre:'Dance', url:''},
{color:'orange', genre:'Dance', url:''},
{color:'yellow', genre:'Dance', url:''},
{color:'yellow', genre:'Dance', url:''},
{color:'yellow', genre:'Dance', url:''},
{color:'yellow', genre:'Dance', url:''},
{color:'yellow', genre:'Dance', url:''},
{color:'green', genre:'Dance', url:''},
{color:'green', genre:'Dance', url:''},
{color:'green', genre:'Dance', url:''},
{color:'green', genre:'Dance', url:''},
{color:'green', genre:'Dance', url:''},
{color:'blue', genre:'Dance', url:''},
{color:'blue', genre:'Dance', url:''},
{color:'blue', genre:'Dance', url:''},
{color:'blue', genre:'Dance', url:''},
{color:'blue', genre:'Dance', url:''},
{color:'purple', genre:'Dance', url:''},
{color:'purple', genre:'Dance', url:''},
{color:'purple', genre:'Dance', url:''},
{color:'purple', genre:'Dance', url:''},
{color:'purple', genre:'Dance', url:''},
{color:'pink', genre:'Dance', url:''},
{color:'pink', genre:'Dance', url:''},
{color:'pink', genre:'Dance', url:''},
{color:'pink', genre:'Dance', url:''},
{color:'pink', genre:'Dance', url:''},

{color:'orange', genre:'Hip/Hop', url:''},
{color:'orange', genre:'Hip/Hop', url:''},
{color:'orange', genre:'Hip/Hop', url:''},
{color:'orange', genre:'Hip/Hop', url:''},
{color:'orange', genre:'Hip/Hop', url:''},
{color:'yellow', genre:'Hip/Hop', url:''},
{color:'yellow', genre:'Hip/Hop', url:''},
{color:'yellow', genre:'Hip/Hop', url:''},
{color:'yellow', genre:'Hip/Hop', url:''},
{color:'yellow', genre:'Hip/Hop', url:''},
{color:'green', genre:'Hip/Hop', url:''},
{color:'green', genre:'Hip/Hop', url:''},
{color:'green', genre:'Hip/Hop', url:''},
{color:'green', genre:'Hip/Hop', url:''},
{color:'green', genre:'Hip/Hop', url:''},
{color:'blue', genre:'Hip/Hop', url:''},
{color:'blue', genre:'Hip/Hop', url:''},
{color:'blue', genre:'Hip/Hop', url:''},
{color:'blue', genre:'Hip/Hop', url:''},
{color:'blue', genre:'Hip/Hop', url:''},
{color:'purple', genre:'Hip/Hop', url:''},
{color:'purple', genre:'Hip/Hop', url:''},
{color:'purple', genre:'Hip/Hop', url:''},
{color:'purple', genre:'Hip/Hop', url:''},
{color:'purple', genre:'Hip/Hop', url:''},
{color:'pink', genre:'Hip/Hop', url:''},
{color:'pink', genre:'Hip/Hop', url:''},
{color:'pink', genre:'Hip/Hop', url:''},
{color:'pink', genre:'Hip/Hop', url:''},
{color:'pink', genre:'Hip/Hop', url:''},

{color:'orange', genre:'R&B', url:''},
{color:'orange', genre:'R&B', url:''},
{color:'orange', genre:'R&B', url:''},
{color:'orange', genre:'R&B', url:''},
{color:'orange', genre:'R&B', url:''},
{color:'yellow', genre:'R&B', url:''},
{color:'yellow', genre:'R&B', url:''},
{color:'yellow', genre:'R&B', url:''},
{color:'yellow', genre:'R&B', url:''},
{color:'yellow', genre:'R&B', url:''},
{color:'green', genre:'R&B', url:''},
{color:'green', genre:'R&B', url:''},
{color:'green', genre:'R&B', url:''},
{color:'green', genre:'R&B', url:''},
{color:'green', genre:'R&B', url:''},
{color:'blue', genre:'R&B', url:''},
{color:'blue', genre:'R&B', url:''},
{color:'blue', genre:'R&B', url:''},
{color:'blue', genre:'R&B', url:''},
{color:'blue', genre:'R&B', url:''},
{color:'purple', genre:'R&B', url:''},
{color:'purple', genre:'R&B', url:''},
{color:'purple', genre:'R&B', url:''},
{color:'purple', genre:'R&B', url:''},
{color:'purple', genre:'R&B', url:''},
{color:'pink', genre:'R&B', url:''},
{color:'pink', genre:'R&B', url:''},
{color:'pink', genre:'R&B', url:''},
{color:'pink', genre:'R&B', url:''},
{color:'pink', genre:'R&B', url:''},

{color:'orange', genre:'Techno', url:''},
{color:'orange', genre:'Techno', url:''},
{color:'orange', genre:'Techno', url:''},
{color:'orange', genre:'Techno', url:''},
{color:'orange', genre:'Techno', url:''},
{color:'yellow', genre:'Techno', url:''},
{color:'yellow', genre:'Techno', url:''},
{color:'yellow', genre:'Techno', url:''},
{color:'yellow', genre:'Techno', url:''},
{color:'yellow', genre:'Techno', url:''},
{color:'green', genre:'Techno', url:''},
{color:'green', genre:'Techno', url:''},
{color:'green', genre:'Techno', url:''},
{color:'green', genre:'Techno', url:''},
{color:'green', genre:'Techno', url:''},
{color:'blue', genre:'Techno', url:''},
{color:'blue', genre:'Techno', url:''},
{color:'blue', genre:'Techno', url:''},
{color:'blue', genre:'Techno', url:''},
{color:'blue', genre:'Techno', url:''},
{color:'purple', genre:'Techno', url:''},
{color:'purple', genre:'Techno', url:''},
{color:'purple', genre:'Techno', url:''},
{color:'purple', genre:'Techno', url:''},
{color:'purple', genre:'Techno', url:''},
{color:'pink', genre:'Techno', url:''},
{color:'pink', genre:'Techno', url:''},
{color:'pink', genre:'Techno', url:''},
{color:'pink', genre:'Techno', url:''},
{color:'pink', genre:'Techno', url:''},

{color:'orange', genre:'Punk Rock', url:''},
{color:'orange', genre:'Punk Rock', url:''},
{color:'orange', genre:'Punk Rock', url:''},
{color:'orange', genre:'Punk Rock', url:''},
{color:'orange', genre:'Punk Rock', url:''},
{color:'yellow', genre:'Punk Rock', url:''},
{color:'yellow', genre:'Punk Rock', url:''},
{color:'yellow', genre:'Punk Rock', url:''},
{color:'yellow', genre:'Punk Rock', url:''},
{color:'yellow', genre:'Punk Rock', url:''},
{color:'green', genre:'Punk Rock', url:''},
{color:'green', genre:'Punk Rock', url:''},
{color:'green', genre:'Punk Rock', url:''},
{color:'green', genre:'Punk Rock', url:''},
{color:'green', genre:'Punk Rock', url:''},
{color:'blue', genre:'Punk Rock', url:''},
{color:'blue', genre:'Punk Rock', url:''},
{color:'blue', genre:'Punk Rock', url:''},
{color:'blue', genre:'Punk Rock', url:''},
{color:'blue', genre:'Punk Rock', url:''},
{color:'purple', genre:'Punk Rock', url:''},
{color:'purple', genre:'Punk Rock', url:''},
{color:'purple', genre:'Punk Rock', url:''},
{color:'purple', genre:'Punk Rock', url:''},
{color:'purple', genre:'Punk Rock', url:''},
{color:'pink', genre:'Punk Rock', url:''},
{color:'pink', genre:'Punk Rock', url:''},
{color:'pink', genre:'Punk Rock', url:''},
{color:'pink', genre:'Punk Rock', url:''},
{color:'pink', genre:'Punk Rock', url:''},

{color:'orange', genre:'Metal', url:''},
{color:'orange', genre:'Metal', url:''},
{color:'orange', genre:'Metal', url:''},
{color:'orange', genre:'Metal', url:''},
{color:'orange', genre:'Metal', url:''},
{color:'yellow', genre:'Metal', url:''},
{color:'yellow', genre:'Metal', url:''},
{color:'yellow', genre:'Metal', url:''},
{color:'yellow', genre:'Metal', url:''},
{color:'yellow', genre:'Metal', url:''},
{color:'green', genre:'Metal', url:''},
{color:'green', genre:'Metal', url:''},
{color:'green', genre:'Metal', url:''},
{color:'green', genre:'Metal', url:''},
{color:'green', genre:'Metal', url:''},
{color:'blue', genre:'Metal', url:''},
{color:'blue', genre:'Metal', url:''},
{color:'blue', genre:'Metal', url:''},
{color:'blue', genre:'Metal', url:''},
{color:'blue', genre:'Metal', url:''},
{color:'purple', genre:'Metal', url:''},
{color:'purple', genre:'Metal', url:''},
{color:'purple', genre:'Metal', url:''},
{color:'purple', genre:'Metal', url:''},
{color:'purple', genre:'Metal', url:''},
{color:'pink', genre:'Metal', url:''},
{color:'pink', genre:'Metal', url:''},
{color:'pink', genre:'Metal', url:''},
{color:'pink', genre:'Metal', url:''},
{color:'pink', genre:'Metal', url:''},

{color:'orange', genre:'Soul', url:''},
{color:'orange', genre:'Soul', url:''},
{color:'orange', genre:'Soul', url:''},
{color:'orange', genre:'Soul', url:''},
{color:'orange', genre:'Soul', url:''},
{color:'yellow', genre:'Soul', url:''},
{color:'yellow', genre:'Soul', url:''},
{color:'yellow', genre:'Soul', url:''},
{color:'yellow', genre:'Soul', url:''},
{color:'yellow', genre:'Soul', url:''},
{color:'green', genre:'Soul', url:''},
{color:'green', genre:'Soul', url:''},
{color:'green', genre:'Soul', url:''},
{color:'green', genre:'Soul', url:''},
{color:'green', genre:'Soul', url:''},
{color:'blue', genre:'Soul', url:''},
{color:'blue', genre:'Soul', url:''},
{color:'blue', genre:'Soul', url:''},
{color:'blue', genre:'Soul', url:''},
{color:'blue', genre:'Soul', url:''},
{color:'purple', genre:'Soul', url:''},
{color:'purple', genre:'Soul', url:''},
{color:'purple', genre:'Soul', url:''},
{color:'purple', genre:'Soul', url:''},
{color:'purple', genre:'Soul', url:''},
{color:'pink', genre:'Soul', url:''},
{color:'pink', genre:'Soul', url:''},
{color:'pink', genre:'Soul', url:''},
{color:'pink', genre:'Soul', url:''},
{color:'pink', genre:'Soul', url:''},

{color:'orange', genre:'Ska', url:''},
{color:'orange', genre:'Ska', url:''},
{color:'orange', genre:'Ska', url:''},
{color:'orange', genre:'Ska', url:''},
{color:'orange', genre:'Ska', url:''},
{color:'yellow', genre:'Ska', url:''},
{color:'yellow', genre:'Ska', url:''},
{color:'yellow', genre:'Ska', url:''},
{color:'yellow', genre:'Ska', url:''},
{color:'yellow', genre:'Ska', url:''},
{color:'green', genre:'Ska', url:''},
{color:'green', genre:'Ska', url:''},
{color:'green', genre:'Ska', url:''},
{color:'green', genre:'Ska', url:''},
{color:'green', genre:'Ska', url:''},
{color:'blue', genre:'Ska', url:''},
{color:'blue', genre:'Ska', url:''},
{color:'blue', genre:'Ska', url:''},
{color:'blue', genre:'Ska', url:''},
{color:'blue', genre:'Ska', url:''},
{color:'purple', genre:'Ska', url:''},
{color:'purple', genre:'Ska', url:''},
{color:'purple', genre:'Ska', url:''},
{color:'purple', genre:'Ska', url:''},
{color:'purple', genre:'Ska', url:''},
{color:'pink', genre:'Ska', url:''},
{color:'pink', genre:'Ska', url:''},
{color:'pink', genre:'Ska', url:''},
{color:'pink', genre:'Ska', url:''},
{color:'pink', genre:'Ska', url:''},

{color:'orange', genre:'Reggae', url:''},
{color:'orange', genre:'Reggae', url:''},
{color:'orange', genre:'Reggae', url:''},
{color:'orange', genre:'Reggae', url:''},
{color:'orange', genre:'Reggae', url:''},
{color:'yellow', genre:'Reggae', url:''},
{color:'yellow', genre:'Reggae', url:''},
{color:'yellow', genre:'Reggae', url:''},
{color:'yellow', genre:'Reggae', url:''},
{color:'yellow', genre:'Reggae', url:''},
{color:'green', genre:'Reggae', url:''},
{color:'green', genre:'Reggae', url:''},
{color:'green', genre:'Reggae', url:''},
{color:'green', genre:'Reggae', url:''},
{color:'green', genre:'Reggae', url:''},
{color:'blue', genre:'Reggae', url:''},
{color:'blue', genre:'Reggae', url:''},
{color:'blue', genre:'Reggae', url:''},
{color:'blue', genre:'Reggae', url:''},
{color:'blue', genre:'Reggae', url:''},
{color:'purple', genre:'Reggae', url:''},
{color:'purple', genre:'Reggae', url:''},
{color:'purple', genre:'Reggae', url:''},
{color:'purple', genre:'Reggae', url:''},
{color:'purple', genre:'Reggae', url:''},
{color:'pink', genre:'Reggae', url:''},
{color:'pink', genre:'Reggae', url:''},
{color:'pink', genre:'Reggae', url:''},
{color:'pink', genre:'Reggae', url:''},
{color:'pink', genre:'Reggae', url:''},

	])
